#include "pugixml.hpp"

#include "set_cover/read_file.hpp"

// construct CRF graph from xml file
WeightedCRFGraph read_from_file(const std::filesystem::path &path)
{
    size_t n, m;
    if (!std::filesystem::exists(path))
    {
        throw std::runtime_error("File not found: " + path.string());
    }
    std::ifstream file{path};
    std::string line;
    do
    {
        std::getline(file, line);
    } while (line.length() == 0 || line[0] == '%');
    std::istringstream iss(line);
    iss >> n >> m;
    int weight_fmt = 0, n_vertex_weights = 0, tmp;
    if (!iss.eof())
    {
        iss >> weight_fmt;
    }
    if (weight_fmt >= 10)
    {
        if (iss.eof())
        {
            n_vertex_weights = 1;
        }
        else
        {
            iss >> n_vertex_weights;
        }
    }
    bool has_edge_weights = weight_fmt % 2 == 1;
    unsigned int u = 0, v = 0;
    auto vertices = std::vector<size_t>(n + 1, 0);
    auto edges = std::vector<size_t>();
    std::vector<double> weights{};
    while (std::getline(file, line))
    {
        if (line[0] == '%')
        {
            continue;
        }
        std::istringstream iss(line);
        for (int i = 0; i < n_vertex_weights; ++i)
        {
            iss >> tmp;
        }
        while ((iss >> v))
        {
            v--; // zero-based indexing
            edges.push_back(v);
            // add_edge(u, v);
            if (has_edge_weights)
            {
                iss >> tmp;
                weights.push_back(static_cast<double>(tmp));
            }
        }
        vertices[u + 1] = edges.size();
        ++u;
    }
    return WeightedCRFGraph{{vertices, edges}, weights};
}

// Construct CSR graph from GraphML file specifically generated by VieCut's mincut cactus output
// Notes:
//  - file includes the function mapping the cactus to the original graph
//  - nodes are zero indexed
//  - it is an undirected graph, but only one direction is stored
// TODO: maybe ifdef if we don't care about this file format to get rid of dependency
WeightedCRFGraph read_from_file_graphML(const std::filesystem::path &path)
{
    if (!std::filesystem::exists(path))
        throw std::runtime_error("File not found: " + path.string());
    pugi::xml_document doc;
    pugi::xml_parse_result result = doc.load_file(path.c_str());
    if (!result)
    {
        throw std::runtime_error("Could not open file " + path.string());
    }
    pugi::xml_node xml_graph = doc.child("graphml").child("graph");
    size_t n_nodes = 0;
    size_t n_edges = 0;
    for (auto &node : xml_graph.children("node"))
    {
        ++n_nodes;
    }
    for (auto &edge : xml_graph.children("edge"))
    {
        ++n_edges;
    }
    // for now just use size_t for indices, but need to improve
    auto vertices = std::vector<size_t>(n_nodes + 1, 0);
    auto edges = std::vector<size_t>();
    auto weights = std::vector<double>();
    // parse contained vertices
    // for (auto &node : xml_graph.children("node"))
    //{
    //    size_t node1 = static_cast<size_t>(node.attribute("id").as_ullong()) - 1;
    //    std::string nodes_string =
    //        node.find_child_by_attribute("key", "containedVertices")
    //            .text()
    //            .as_string();

    //    std::stringstream ss(nodes_string);
    //    std::string item;
    //    while (getline(ss, item, ','))
    //    {
    //        size_t node2 = std::stoul(item) - 1;
    //        edges.emplace_back(node2);
    //        graph.map_to_original_graph[cactus_node_id + 1].push_back(nd + 1);
    //        graph.map_to_cactus[nd + 1] = cactus_node_id + 1;
    //    }
    //}

    auto adj_list = std::vector<std::vector<std::pair<size_t, double>>>(n_nodes, std::vector<std::pair<size_t, double>>{});

    // parse edges
    for (auto &edge : xml_graph.children("edge"))
    {
        double weight =
            edge.find_child_by_attribute("key", "weight").text().as_double();
        size_t source = edge.attribute("source").as_ullong();
        size_t target = edge.attribute("target").as_ullong();
        adj_list[source].emplace_back(target, weight);
        adj_list[target].emplace_back(source, weight);
    }
    for (size_t u = 0; u < adj_list.size(); u++)
    {
        for (auto &neighbor : adj_list[u])
        {
            weights.emplace_back(neighbor.second);
            edges.emplace_back(neighbor.first);
        }
        vertices[u + 1] = edges.size();
    }
    return {{vertices, edges}, weights};
}
